#!/bin/sh
#
# PROVIDE: pcloudd
# REQUIRE: LOGIN NETWORKING FILESYSTEMS
# KEYWORD: shutdown
#

. /etc/rc.subr

name="pcloudd"
rcvar="pcloudd_enable"

: ${pcloudd_enable:="NO"}
: ${pcloudd_user:="pcloud-rs"}
: ${pcloudd_env_file:="/usr/local/etc/pcloudd.env"}
: ${pcloudd_wrapper:="/usr/local/libexec/pcloudd-wrapper.sh"}
: ${pcloudd_pidfile:="/var/run/${name}.pid"}

command="/usr/sbin/daemon"
command_args="-f -P ${pcloudd_pidfile} ${pcloudd_wrapper}"
pidfile="${pcloudd_pidfile}"
required_files="${pcloudd_wrapper}"

start_precmd="pcloudd_precmd"

pcloudd_precmd()
{
    [ -r "${pcloudd_env_file}" ] && . "${pcloudd_env_file}"
    export PCLOUD_ROOT PCLOUD_ENV PCLOUD_API_MODE PCLOUD_DURABLE_AUTH_TOKENS
    export PCLOUDRS_TOKEN_FILE PCLOUDRS_USERNAME_FILE PCLOUDRS_PASSWORD_FILE
    export PCLOUDRS_TFA_CODE_FILE PCLOUDRS_RECOVERY_CODE_FILE PCLOUDRS_TRUST_DEVICE
    export PCLOUDRS_DAEMON_BIN
}

load_rc_config $name
run_rc_command "$1"
