#!/bin/sh
#
# PROVIDE: pcloudd
# REQUIRE: DAEMON network
# KEYWORD: shutdown
#

. /etc/rc.subr

name="pcloudd"
rcvar=$name
command="/usr/pkg/bin/daemon"
command_args="-p /var/run/${name}.pid /usr/local/libexec/pcloudd-wrapper.sh"
pidfile="/var/run/${name}.pid"
required_files="/usr/local/libexec/pcloudd-wrapper.sh"

start_precmd="pcloudd_precmd"

pcloudd_precmd()
{
    [ -r /usr/pkg/etc/pcloudd.env ] && . /usr/pkg/etc/pcloudd.env
    export PCLOUD_ROOT PCLOUD_ENV PCLOUD_API_MODE PCLOUD_DURABLE_AUTH_TOKENS
    export PCLOUDRS_TOKEN_FILE PCLOUDRS_USERNAME_FILE PCLOUDRS_PASSWORD_FILE
    export PCLOUDRS_TFA_CODE_FILE PCLOUDRS_RECOVERY_CODE_FILE PCLOUDRS_TRUST_DEVICE
    export PCLOUDRS_DAEMON_BIN
}

load_rc_config $name
run_rc_command "$1"
